# -*- coding: utf-8 -*-
"""Aula 16-10-2023.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R5S82vMOuobn3NVDtfLxq_oTm_QthP4b
"""

import pandas as pd

df = pd.read_csv('sarespv1.csv')

basico_serie = df[df['classification'] == 'Básico']
series = ["5º Ano EF", "7º Ano EF", "9º Ano EF", "EM-3ª série"]
quantidade_basico_por_serie = basico_serie[basico_serie['SERIE_ANO'].isin(series)].groupby('SERIE_ANO').size()

classificacoes = ["Abaixo do Básico", "Básico", "Adequado", "Avançado"]
quantidade_por_classificacao_serie = df[df['SERIE_ANO'].isin(series)].groupby(['SERIE_ANO', 'classification']).size()

escola_professor = df[df['NOMESC'] == 'ANTONIO BRASILIO MENEZES DA FONSECA PROFESSOR']
escola_prof = df[df['NOMESC'] == 'ANTONIO BRASILIO MENEZES DA FONSECA PROF']

medprof_professor = escola_professor['medprof'].mean()
avancado_count_professor = (escola_professor['classification'] == 'Avançado').sum()
total_alunos_professor = len(escola_professor)
avancado_majority_professor = avancado_count_professor / total_alunos_professor > 0.5

medprof_prof = escola_prof['medprof'].mean()
avancado_count_prof = (escola_prof['classification'] == 'Avançado').sum()
total_alunos_prof = len(escola_prof)
avancado_majority_prof = avancado_count_prof / total_alunos_prof > 0.5

print("Quantidade de alunos com classificação 'Básico' por série:")
print(quantidade_basico_por_serie)
print("\nQuantidade de alunos por classificação e série:")
print(quantidade_por_classificacao_serie)
print("\nAnálise da escola 'ANTONIO BRASILIO MENEZES DA FONSECA PROFESSOR':")
print(f"Média de Proficiência (medprof): {medprof_professor}")
print(f"Quantidade de alunos 'Avançado': {avancado_count_professor}")
print(f"Proporção de alunos 'Avançado' na escola: {avancado_count_professor / total_alunos_professor:.2%}")
print(f"A maioria dos alunos obteve 'Avançado': {avancado_majority_professor}")
print("\nAnálise da escola 'ANTONIO BRASILIO MENEZES DA FONSECA PROF':")
print(f"Média de Proficiência (medprof): {medprof_prof}")
print(f"Quantidade de alunos 'Avançado': {avancado_count_prof}")
print(f"Proporção de alunos 'Avançado' na escola: {avancado_count_prof / total_alunos_prof:.2%}")
print(f"A maioria dos alunos obteve 'Avançado': {avancado_majority_prof}")